### ISSUE TITLE
GUI - a page displaying logShell output

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#32]
should be dynamically reloading the last 40 entries of the table and displaying them <PRE> formatted</pre>

**Comment by tlwt** [comment]
linked to #31

**Comment by jannik-kramer** [comment]
~~closed by #34~~
wrong commit/pull request

**Comment by jannik-kramer** [comment]
closed by 0bcbcef9348539f94f22b1880f6ba6889852c740
