### ISSUE TITLE
running on different port then 80 causes link to phpliteadmin to fail

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#44]
Apparently a slash needs to be added at the end - otherwise the routing of the framework picks it up.

**Odd behaviour:**
* Link goes to:   
`http://192.168.1.5:40080/phpliteadmin` => does not work - redirected to  `http://192.168.1.5/phpliteadmin`
* `http://192.168.1.5:40080/phpliteadmin` => seems to work

**Comment by jannik-kramer** [comment]
Did you changed the `listen` directive in the nginx config to run on the different port?
The /phpliteadmin link should be catched by nginx and should not even invoke the framework at all.
