### ISSUE TITLE
cannot insert new subject rule

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#45]
Tried to install new subject rule - did not work (no error message). Adding new recipient worked fine ...

attached my db table structure

```
CREATE TABLE "rule_subjects" ( `id`	INTEGER PRIMARY KEY AUTOINCREMENT, `foundWords`	TEXT, `foundCompany`	TEXT, `fileSubject`	TEXT, `subjectScore`	INTEGER NOT NULL DEFAULT (0), `tags` TEXT, `isActive` INTEGER NOT NULL DEFAULT (1), updated_at TEXT, created_at TEXT )
```

**Comment by jannik-kramer** [comment]
Did you filled out every field?
Error messages are not merged yet.

**Comment by tlwt** [comment]
Nope - company was empty. With it filled, it works.
But it should be ok to have that one not filled, as it may be a generic rule.
