### ISSUE TITLE
add "booting - please wait" page

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#46]
In Dockerfile the following line
```
composer install --no-interaction &>/dev/null
```
takes quite some time. Until this the system does not boot up / show up correctly.

Idea: add a static index.html with a nice "please wait, paperyard is booting (only once)" info. This should reload every five seconds and indicate how long it usually takes.

if we add a line in the start.sh after the long loader:
```
rm index.html
```

this should remove it once down and the actual system boots up.

**Comment by jannik-kramer** [comment]
This will also take some time everytime we add some dependencies. Either we add a way of detecting the boot in general, or we just move the `composer install` part above the nginx start.

**Comment by tlwt** [comment]
Anything giving a quicker responds to the user is ok for the time being. Please give it a shot.
