### ISSUE TITLE
combine PDF documents

### ISSUE THREAD

**Issue by jannik-kramer** [tlwt/paperyard#49]

**Comment by tlwt** [comment]
we need a system to merge two or more PDF documents (e.g. doc1.pdf and doc2.pdf). 

When selecting documents for merge, different merge strategies should be allowed:
* all pages of doc1 followed by all pages of doc2 (or vice versa)
* interleaved pages: page1 of doc1, then page 1 of doc2, then page2 of doc1, then page2 of doc2 (or vice versa)

**Comment by tlwt** [comment]
This could be implemented on a bash / or other tooling level which is callable from the frontend. Does not necessarily need to be PHP.
