### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#51]
`DataTables warning: table id=DataTables_Table_0 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3`

when calling http://localhost/rules/senders

**Comment by tlwt** [comment]
apparently the database was not up-to-date. We need to check somehow that the front-end and back-end match in terms of version number ...

**Comment by jannik-kramer** [comment]
This due to and merging mistake. This is unrelated to the sqlite database and its version. The warning occurs because some old scripts survived the merge and causing the datatables plugin to initialize twice.
