### ISSUE TITLE
Dashboard content

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#54]
The dashboard should show:

* the number of files where OCR failed and ask what to do with them
* then it should show the number of files still to process

... and probably more. Lets discuss here.

**Comment by jannik-kramer** [comment]
b282614bb823dd3a6c2fb986ac70b7ef795eb948 and 3166e187abd6523cc8989d936d5d818dfa4b3f5f added a bit. At least the row is filled now. More ideas?
