### ISSUE TITLE
visual feedback for file upload success or failure

### ISSUE THREAD

**Issue by jannik-kramer** [tlwt/paperyard#69]

**Comment by kosalaindrasiri** [comment]
What kind of feedback you want to show? Spinner or progress bar? Do you have any mockup for this?

**Comment by jannik-kramer** [comment]
Using `fa-spinner fa-spin` as the icon on the upload widget should be enough to indicate that the upload is going on. We already have [bootstrap-notify](http://bootstrap-notify.remabledesigns.com/) in place. Please use it to give feedback on failure or success.
