### ISSUE TITLE
go back to last document

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#76]
as usual - once pressed confirmed I notice something wrong ... so a back button would be nice.

**Comment by jannik-kramer** [comment]
Somewhat tricky. We need to work out the indexer.

Thoughts on this:
As soon as you hit confirm, the "ok" tag is set. So at any given time, the sorter could move it. Currently, if you hit that back button and the file isn't found anymore in the outbox/inbox, the system would have to do some sort of back propagation to find the file in the sort/archive and bring it back.
With the indexer in place, the system could take you to the document details view so you could edit it there.
