### ISSUE TITLE
SQL error when trying to view home page

### ISSUE THREAD

**Issue by kosalaindrasiri** [tlwt/paperyard#90]
> Type: Illuminate\Database\QueryException
> Code: HY000
> Message: SQLSTATE[HY000]: General error: 14 unable to open database file (SQL: select distinct "fileContent" from "logs")
> File: /paperyardSrc/paperyard/paperyard/frontend/vendor/illuminate/database/Connection.php
> Line: 664

**Comment by jannik-kramer** [comment]
Most likely this will be a file permissions problem. Take a look at the dockerRun.sh and make sure the specified paths are read and writeable by the docker daemon.
Btw, which os are you running?

**Comment by kosalaindrasiri** [comment]
I am using Ubuntu 16.04.

**Comment by kosalaindrasiri** [comment]
@jannik-kramer I tried to giving permission for docker daemon. Still no work.

**Comment by kosalaindrasiri** [comment]
Manually set permission of `/data` folder to `777` in docker container fixed the issue.
